name: flame_gamejam3
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  flame: ^1.12.0
  flame_audio: ^2.1.4
  flame_bloc: ^1.10.10
  flame_forge2d: ^0.16.0+2
  flame_mini_sprite: ^0.0.1
  mini_sprite: ^0.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1

  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/music/
    - assets/sfx/
    - assets/images/
